// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/measure_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:mobile/models/enum/bird_event_type.dart' as _i8;
import 'package:mobile/models/enum/bird_specie.dart' as _i7;
import 'package:mobile/models/enum/weather_type.dart' as _i6;
import 'package:mobile/repositories/measure_repository.dart' as _i3;
import 'package:mobile/web_providers/measure_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMeasureProvider_0 extends _i1.SmartFake
    implements _i2.MeasureProvider {
  _FakeMeasureProvider_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MeasureRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeasureRepository extends _i1.Mock implements _i3.MeasureRepository {
  MockMeasureRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MeasureProvider get measureProvider =>
      (super.noSuchMethod(
            Invocation.getter(#measureProvider),
            returnValue: _FakeMeasureProvider_0(
              this,
              Invocation.getter(#measureProvider),
            ),
          )
          as _i2.MeasureProvider);

  @override
  _i4.Future<dynamic> getUserMeasures() =>
      (super.noSuchMethod(
            Invocation.method(#getUserMeasures, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> getSingleMeasure(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getSingleMeasure, [id]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> createTemperature(
    DateTime? date,
    String? location,
    int? degree,
    _i5.File? picture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTemperature, [
              date,
              location,
              degree,
              picture,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> createSnowHeight(
    DateTime? date,
    String? location,
    int? height,
    _i6.WeatherType? weather,
    int? precipitation,
    _i5.File? picture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSnowHeight, [
              date,
              location,
              height,
              weather,
              precipitation,
              picture,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> createBirdMigration(
    DateTime? date,
    String? location,
    _i7.BirdSpecie? specie,
    _i8.BirdEventType? event,
    _i5.File? picture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBirdMigration, [
              date,
              location,
              specie,
              event,
              picture,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> createEggsLaying(
    DateTime? date,
    String? location,
    int? number,
    _i5.File? picture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createEggsLaying, [
              date,
              location,
              number,
              picture,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> updateTemperature(
    int? measureId,
    DateTime? date,
    String? location,
    int? degree,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTemperature, [
              measureId,
              date,
              location,
              degree,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> updateSnowHeight(
    int? measureId,
    DateTime? date,
    String? location,
    int? height,
    _i6.WeatherType? weather,
    int? precipitation,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateSnowHeight, [
              measureId,
              date,
              location,
              height,
              weather,
              precipitation,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> updateBirdMigration(
    int? measureId,
    DateTime? date,
    String? location,
    _i7.BirdSpecie? specie,
    _i8.BirdEventType? event,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBirdMigration, [
              measureId,
              date,
              location,
              specie,
              event,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> updateEggsLaying(
    int? measureId,
    DateTime? date,
    String? location,
    int? number,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEggsLaying, [
              measureId,
              date,
              location,
              number,
            ]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> deleteMeasure(int? measureId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMeasure, [measureId]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}
