// Mocks generated by Mockito 5.4.6 from annotations
// in mobile/test/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mobile/repositories/user_repository.dart' as _i3;
import 'package:mobile/web_providers/user_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserProvider_0 extends _i1.SmartFake implements _i2.UserProvider {
  _FakeUserProvider_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserProvider get userProvider =>
      (super.noSuchMethod(
            Invocation.getter(#userProvider),
            returnValue: _FakeUserProvider_0(
              this,
              Invocation.getter(#userProvider),
            ),
          )
          as _i2.UserProvider);

  @override
  _i4.Future<dynamic> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> createUser(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [name, email, password]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> loginUser(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#loginUser, [email, password]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> updateUser(
    String? name,
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [name, email, password]),
            returnValue: _i4.Future<dynamic>.value(),
          )
          as _i4.Future<dynamic>);
}
